import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';
import { QueryResult } from './databaseManager';

export class ExportManager {
    constructor() {}

    async saveResults(results: QueryResult[], query: string, templateName?: string): Promise<string> {
        const config = vscode.workspace.getConfiguration('cursorSqlRunner');
        const outputDir = config.get<string>('outputDirectory', './cursor-query-results');
        const format = config.get<string>('resultFormat', 'json');
        
        // Create filename
        const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
        const baseName = templateName ? 
            `${templateName.replace(/[^a-zA-Z0-9]/g, '_')}_${timestamp}` : 
            `query_result_${timestamp}`;
        
        const fileName = `${baseName}.${format}`;
        const workspaceRoot = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath || '';
        const fullPath = path.join(workspaceRoot, outputDir, fileName);

        // Ensure directory exists
        const dirPath = path.dirname(fullPath);
        if (!fs.existsSync(dirPath)) {
            fs.mkdirSync(dirPath, { recursive: true });
        }

        // Save in requested format
        switch (format) {
            case 'json':
                await this.saveAsJSON(fullPath, results, query, templateName);
                break;
            case 'csv':
                await this.saveAsCSV(fullPath, results, query, templateName);
                break;
            case 'html':
                await this.saveAsHTML(fullPath, results, query, templateName);
                break;
            case 'txt':
                await this.saveAsText(fullPath, results, query, templateName);
                break;
            default:
                await this.saveAsJSON(fullPath, results, query, templateName);
        }

        return fileName;
    }

    private async saveAsJSON(filePath: string, results: QueryResult[], query: string, templateName?: string): Promise<void> {
        const output = {
            metadata: {
                timestamp: new Date().toISOString(),
                templateName: templateName || 'Custom Query',
                query: query,
                resultCount: results.length,
                generatedBy: 'Cursor SQL Runner Extension'
            },
            results: results
        };

        fs.writeFileSync(filePath, JSON.stringify(output, null, 2), 'utf8');
    }

    private async saveAsCSV(filePath: string, results: QueryResult[], query: string, templateName?: string): Promise<void> {
        if (results.length === 0) {
            fs.writeFileSync(filePath, '# No results found\n', 'utf8');
            return;
        }

        // Get headers from first result
        const headers = Object.keys(results[0]);
        
        // Create CSV content
        let csvContent = '';
        
        // Add metadata as comments
        csvContent += `# Generated by: Cursor SQL Runner Extension\n`;
        csvContent += `# Timestamp: ${new Date().toISOString()}\n`;
        csvContent += `# Template: ${templateName || 'Custom Query'}\n`;
        csvContent += `# Query: ${query.replace(/\n/g, ' ')}\n`;
        csvContent += `# Results: ${results.length} rows\n#\n`;
        
        // Add headers
        csvContent += headers.map(h => this.escapeCSV(h)).join(',') + '\n';
        
        // Add data rows
        for (const row of results) {
            const values = headers.map(header => {
                const value = row[header];
                return this.escapeCSV(value !== null && value !== undefined ? String(value) : '');
            });
            csvContent += values.join(',') + '\n';
        }

        fs.writeFileSync(filePath, csvContent, 'utf8');
    }

    private async saveAsHTML(filePath: string, results: QueryResult[], query: string, templateName?: string): Promise<void> {
        const htmlContent = this.generateHTML(results, query, templateName);
        fs.writeFileSync(filePath, htmlContent, 'utf8');
    }

    private async saveAsText(filePath: string, results: QueryResult[], query: string, templateName?: string): Promise<void> {
        let content = '';
        
        // Add metadata
        content += '='.repeat(60) + '\n';
        content += 'CURSOR SQL QUERY RESULTS\n';
        content += '='.repeat(60) + '\n';
        content += `Generated: ${new Date().toISOString()}\n`;
        content += `Template: ${templateName || 'Custom Query'}\n`;
        content += `Results: ${results.length} rows\n\n`;
        content += 'Query:\n';
        content += '-'.repeat(30) + '\n';
        content += query + '\n\n';
        content += 'Results:\n';
        content += '-'.repeat(30) + '\n';

        if (results.length === 0) {
            content += 'No results found.\n';
        } else {
            // Format as table
            const headers = Object.keys(results[0]);
            const columnWidths = headers.map(header => {
                const maxValueLength = Math.max(
                    ...results.map(row => String(row[header] || '').length)
                );
                return Math.max(header.length, maxValueLength, 10);
            });

            // Header row
            content += '| ';
            headers.forEach((header, i) => {
                content += header.padEnd(columnWidths[i]) + ' | ';
            });
            content += '\n';

            // Separator row
            content += '|';
            columnWidths.forEach(width => {
                content += '-'.repeat(width + 2) + '|';
            });
            content += '\n';

            // Data rows
            results.forEach(row => {
                content += '| ';
                headers.forEach((header, i) => {
                    const value = row[header] !== null && row[header] !== undefined ? 
                        String(row[header]) : '';
                    content += value.padEnd(columnWidths[i]) + ' | ';
                });
                content += '\n';
            });
        }

        content += '\n' + '='.repeat(60) + '\n';
        content += `End of results (${results.length} rows)\n`;

        fs.writeFileSync(filePath, content, 'utf8');
    }

    private generateHTML(results: QueryResult[], query: string, templateName?: string): string {
        return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cursor SQL Query Results - ${templateName || 'Custom Query'}</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 20px;
            background-color: #f5f5f5;
            color: #333;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 30px;
        }
        .header h1 {
            margin: 0 0 10px 0;
            font-size: 2em;
        }
        .header p {
            margin: 5px 0;
            opacity: 0.9;
        }
        .query-section {
            background: #f8f9fa;
            border: 1px solid #e9ecef;
            border-radius: 5px;
            padding: 15px;
            margin-bottom: 20px;
        }
        .query-section h3 {
            margin-top: 0;
            color: #495057;
        }
        .query-code {
            background: #2d3748;
            color: #e2e8f0;
            padding: 15px;
            border-radius: 5px;
            font-family: 'Consolas', 'Monaco', monospace;
            white-space: pre-wrap;
            overflow-x: auto;
        }
        .results-section {
            margin-top: 30px;
        }
        .stats {
            background: #e3f2fd;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
            display: flex;
            justify-content: space-around;
            text-align: center;
        }
        .stat-item {
            flex: 1;
        }
        .stat-number {
            font-size: 2em;
            font-weight: bold;
            color: #1976d2;
        }
        .stat-label {
            font-size: 0.9em;
            color: #666;
            text-transform: uppercase;
            letter-spacing: 1px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            font-size: 14px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }
        th {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            font-weight: 600;
            position: sticky;
            top: 0;
            z-index: 10;
        }
        tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        tr:hover {
            background-color: #e3f2fd;
        }
        .no-results {
            text-align: center;
            padding: 40px;
            color: #666;
            font-style: italic;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            color: #666;
            border-top: 1px solid #eee;
            padding-top: 20px;
        }
        .json-toggle {
            margin-top: 20px;
            text-align: center;
        }
        .json-data {
            display: none;
            background: #2d3748;
            color: #e2e8f0;
            padding: 20px;
            border-radius: 5px;
            margin-top: 10px;
            overflow-x: auto;
            white-space: pre-wrap;
            font-family: 'Consolas', 'Monaco', monospace;
            font-size: 12px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🗄️ Cursor SQL Query Results</h1>
            <p><strong>Template:</strong> ${templateName || 'Custom Query'}</p>
            <p><strong>Generated:</strong> ${new Date().toISOString()}</p>
            <p><strong>Extension:</strong> Cursor SQL Runner</p>
        </div>

        <div class="query-section">
            <h3>📝 Query</h3>
            <div class="query-code">${this.escapeHtml(query)}</div>
        </div>

        <div class="results-section">
            <h3>📊 Results</h3>
            
            <div class="stats">
                <div class="stat-item">
                    <div class="stat-number">${results.length}</div>
                    <div class="stat-label">Total Rows</div>
                </div>
                <div class="stat-item">
                    <div class="stat-number">${results.length > 0 ? Object.keys(results[0]).length : 0}</div>
                    <div class="stat-label">Columns</div>
                </div>
                <div class="stat-item">
                    <div class="stat-number">${(JSON.stringify(results).length / 1024).toFixed(1)}KB</div>
                    <div class="stat-label">Data Size</div>
                </div>
            </div>

            ${results.length === 0 ? 
                '<div class="no-results">No results found for this query.</div>' :
                this.generateTable(results)
            }
        </div>

        ${results.length > 0 ? `
        <div class="json-toggle">
            <button onclick="toggleJson()" style="background: #667eea; color: white; border: none; padding: 10px 20px; border-radius: 5px; cursor: pointer;">
                Toggle JSON Data
            </button>
            <div id="json-data" class="json-data">${this.escapeHtml(JSON.stringify(results, null, 2))}</div>
        </div>
        ` : ''}

        <div class="footer">
            <p>Generated by <strong>Cursor SQL Runner Extension</strong></p>
            <p>Timestamp: ${new Date().toISOString()}</p>
        </div>
    </div>

    <script>
        function toggleJson() {
            const jsonData = document.getElementById('json-data');
            jsonData.style.display = jsonData.style.display === 'none' ? 'block' : 'none';
        }
    </script>
</body>
</html>`;
    }

    private generateTable(results: QueryResult[]): string {
        if (results.length === 0) {
            return '<p>No results to display.</p>';
        }

        const headers = Object.keys(results[0]);
        
        let tableHtml = '<table><thead><tr>';
        headers.forEach(header => {
            tableHtml += `<th>${this.escapeHtml(header)}</th>`;
        });
        tableHtml += '</tr></thead><tbody>';

        results.forEach(row => {
            tableHtml += '<tr>';
            headers.forEach(header => {
                const value = row[header];
                const displayValue = value !== null && value !== undefined ? String(value) : '';
                tableHtml += `<td>${this.escapeHtml(displayValue)}</td>`;
            });
            tableHtml += '</tr>';
        });

        tableHtml += '</tbody></table>';
        return tableHtml;
    }

    private escapeHtml(text: string): string {
        return text
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&#39;');
    }

    private escapeCSV(value: string): string {
        if (value.includes(',') || value.includes('"') || value.includes('\n')) {
            return `"${value.replace(/"/g, '""')}"`;
        }
        return value;
    }
}
